version: '3'

services:
  db:
    build:
      context: ../../images/db
      dockerfile: Dockerfile
    ports:
     - 5432:5432
    env_file: .env
    volumes:
       - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8081:8080

volumes:
  db-data:
