#!/bin/sh

<<<<<<< HEAD
psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'CREATE USER ${CHAT_USER} WITH ENCRYPTED PASSWORD ${CHAT_PASSWORD}'
=======
psql ${POSTGRES_DB} -U ${POSTGRES_USER} -c 'CREATE USER ${CHAT_USER} WITH ENCRYPTED PASSWORD ${CHAT_PASSWORD}'
>>>>>>> 14192aecfd61a5ee810cef701de2f401feb4ffec
